language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm config set spin false
install: yarn install

jobs:
  include:
    - stage: build
      script: yarn run build
    - stage: deploy
      script: yarn run deploy
      on:
        branch: master