language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - "$HOME/.npm"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8
install: yarn install

jobs:
  include:
    - stage: build
      script: yarn run build
    - stage: deploy
      script: yarn run deploy
      on:
        branch: master