language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - "$HOME/.npm"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8
install: yarn install
script: yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master